# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d510dd2a9267c1238cd9dadc32e3c96c2a511d95e104144001f0a725a680b16d5473e783c930aa7bf46a310bf7c686967b40f46c529359641935a27e44adb9a2

test:
  secret_key_base: dc70c689b9d10c619d27e18a13ce736a40eef9e35c5f5f91ab9edadf8bc6de8d5ea7efab94af6cec2ee9296a1d7be73da335165b4004c9cb161bb80b1e0e2ca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
